### ISSUE TITLE
the calendar open behind the modal mask

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-calendars#5]
Hi,

We use the modal mask from ng-bootstrap. When you open the ej2-ng-datepicker calendar, the calendar is behind the modal mask.

Regards
j.nord

**Comment by SasikalaNagarajan** [comment]
Hi 

Thanks for your interest in Essential JS 2. We have looked into your inquiry on “ej2-ng-datepicker, the calendar is behind the modal mask” and the root cause of this issue is due to the z-index value of the modal mask being higher than the z-index of the calendar. We are not dynamically setting the higher z-index of the component in the source because calculating the higher z-index in component might cause the performance loss in the application.

As a solution therefore, we suggest that you to go on application side to set the z-index of the component by using the code given in the following sample link.

Sample Link: https://github.com/SasikalaNagarajan/mask-calendar

This should help resolve the issue. Please let us know if you need further assistance.

Regards,

Sasikala Nagarajan

**Comment by j-nord** [comment]
Hi,

it doesn't work:

TypeError: Cannot read property 'classList' of null at NHDatepicker.onClose (http://localhost:54962/dist/app.bundle.js:258162:43) at Object.eval [as handleEvent] (ng:///NHBasisModule/NHDatepicker.ngfactory.js:44:27) at handleEvent (http://localhost:54962/dist/app.bundle.js:12334:138) at 

because the id "overlay" not in the DOM.

Also we want not use "document" in the code because we want it should run under Angular Universal in the future.

Since we change to the version 15.4.7 the local L10n translation doesn't work.

How can we get a solution:
- running under ng-bootstrap modal mask
- call it und anugular universal
- and the local L10n run again

Regards

j.nord

**Comment by manikandan05** [comment]
Hi,

The sample we have previously provided the custom element (overlay) to act as backdrop. But that element is not present in your application. So, that it throws the error. However now we have modified the sample to achieve your requirement **“show the popup element over the backdrop (bootstrap) element”**.

Here, we have explained z-index calculation related code blocks in **model-basic.ts** file. Also, we have addressed your L10n query by rendering the DatePicker component in **German** culture. In **app.component.ts** we have explained how to load and utilize the culture (**cldr-data**) related files.

Sample Link: [https://github.com/SasikalaNagarajan/mask-calendar](https://github.com/SasikalaNagarajan/mask-calendar)

To know more about DatePicker component please refer the following online documentation and demos samples link.

[http://ej2.syncfusion.com/15.4.17/angular/demos/#/material/datepicker/default](http://ej2.syncfusion.com/15.4.17/angular/demos/#/material/datepicker/default)

[http://ej2.syncfusion.com/15.4.17/angular/documentation/datepicker/getting-started.html](http://ej2.syncfusion.com/15.4.17/angular/documentation/datepicker/getting-started.html)

Please let us know if you need further assistance.

Regards,
Manikandan Mariappan
