### ISSUE TITLE
DatePicker empty for current month

### ISSUE THREAD

**Issue by oxxa** [syncfusion/ej2-ng-calendars#6]
In the example http://ej2.syncfusion.com/15.4.17/angular/demos/#/material/datepicker/default  and in my local project the datepicker shows no dates in the current month.

**Comment by SasikalaNagarajan** [comment]
Hi,

Thanks for your interest in Essential JS 2. We have looked into your query “DatePicker doesn’t show dates in current month” and tried in our sample, but we are unable to reproduce the reported issue. However, we suspect that the cause of the issue might be CSS not properly referred/loaded in a page or else any other script error might have occurred. If you got any script error please share screenshot or error information to check on that further. 

Also, if you had any other issue, please try the steps given from the Getting start guidelines in our documentation to get rid of component rendering issue. 

Documentation Link: http://ej2.syncfusion.com/15.4.17/angular/documentation/datepicker/getting-started.html 

Also, we have prepared the sample and updated in below link. Please check it. 
 
Sample Link: https://github.com/SasikalaNagarajan/DatePicker
 
If the issue persists, please revert with more information along with an issue reproducing sample (if possible) so that we can provide the exact solution for your requirement. 
 
Regards, 

Sasikala Nagarajan

**Comment by oxxa** [comment]
Hi Sasikala,

I have just run your example and I still see no dates in the current month.  I also see the same empty month when using the example from your documentation page ( http://ej2.syncfusion.com/15.4.17/angular/documentation/datepicker/getting-started.html ) .  Note that the second example on that page where the date is pre-selected *does* show dates.  See below of what I am seeing - I see this in IE, Edge, Firefox, Chrome & Vivaldi.  I have turned all adblockers etc off and I see no errors in console or css)

![emptycalendar](https://user-images.githubusercontent.com/20371749/32982782-ca98c2f2-cc81-11e7-8cb7-188ce5856f3a.gif)

**Comment by Sureshkumar2288** [comment]
Hi Jonesy,

Sorry for the inconvenience caused.

we can reproduce the issue. We have considered this ‘**datepicker shows no dates in the current month**’ as a bug and logged a report for the same. The fix will be available in our November 30, 2017 release.

Regards,
Sureshkumar P

**Comment by Sureshkumar2288** [comment]
Hi Jonesy,
  
We are glad to announce that our Essential JavaScript 2 Release is rolled out and is available for download at the following link.  
 
Latest build: Syncfusion JS2 components  
  
Also, the fix for “datepicker shows no dates in the current month” is included in the above version. 
 
We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.  
 
Regards,  
Sureshkumar P

**Comment by oxxa** [comment]
Thanks for the fix, confirmed in build .20
