### ISSUE TITLE
firstDayOfWeek of the week doesn't work

### ISSUE THREAD

**Issue by j-nord** [syncfusion/ej2-ng-calendars#7]
Hi,

when we set firstDayOfWeek = "1" the datepicker doesn't work and angular hangs.

Regards

j.nord

**Comment by berlybrightly** [comment]
Hi,

Thanks for your interest in Essential JS 2. We have looked into your query “**firstDayOfWeek of the week doesn't work**”. We suspected that root cause of this issue due to type of the firstDayofWeek API has been assigned as **string** in your application. But, the type of fisrtDayofWeek is **number**. So, we are suggesting you to assign this API as number type in your application to avoid the reported issue.

For your convenience, we have prepared the sample based on your requirement. Please get the sample from the below link.

**Sample Link:** http://plnkr.co/edit/HqSzs2S7tsYnzRY0EKVp?p=preview

To know more about our API’s, methods and events of our DatePicker component please refer the below UG Documentation link.

**UG Link**: http://ej2.syncfusion.com/15.4.17/documentation/datepicker/api-datePicker.html?lang=typescript#firstdayofweek-number

Regards,
Berly B.C

**Comment by j-nord** [comment]
Hi,

Thank's for the answer! So it works.

Regards
j.nord
